hep_sub ./script/fit_total_nonlin.sh -o log -e log -argu 5
hep_sub ./script/fit_total_nonlin.sh -o log -e log -argu 13
hep_sub ./script/fit_total_nonlin.sh -o log -e log -argu 15
hep_sub ./script/fit_total_nonlin.sh -o log -e log -argu 33
hep_sub ./script/fit_total_nonlin.sh -o log -e log -argu 40
hep_sub ./script/fit_total_nonlin.sh -o log -e log -argu 41
hep_sub ./script/fit_total_nonlin.sh -o log -e log -argu 42
hep_sub ./script/fit_total_nonlin.sh -o log -e log -argu 43
hep_sub ./script/fit_total_nonlin.sh -o log -e log -argu 44
hep_sub ./script/fit_total_nonlin.sh -o log -e log -argu 45
hep_sub ./script/fit_total_nonlin.sh -o log -e log -argu 46
hep_sub ./script/fit_total_nonlin.sh -o log -e log -argu 47
hep_sub ./script/fit_total_nonlin.sh -o log -e log -argu 49
hep_sub ./script/fit_total_nonlin.sh -o log -e log -argu 50
hep_sub ./script/fit_total_nonlin.sh -o log -e log -argu 53
hep_sub ./script/fit_total_nonlin.sh -o log -e log -argu 54
hep_sub ./script/fit_total_nonlin.sh -o log -e log -argu 75
hep_sub ./script/fit_total_nonlin.sh -o log -e log -argu 78
hep_sub ./script/fit_total_nonlin.sh -o log -e log -argu 79
hep_sub ./script/fit_total_nonlin.sh -o log -e log -argu 80
hep_sub ./script/fit_total_nonlin.sh -o log -e log -argu 81
hep_sub ./script/fit_total_nonlin.sh -o log -e log -argu 82
hep_sub ./script/fit_total_nonlin.sh -o log -e log -argu 83
hep_sub ./script/fit_total_nonlin.sh -o log -e log -argu 84
hep_sub ./script/fit_total_nonlin.sh -o log -e log -argu 86
hep_sub ./script/fit_total_nonlin.sh -o log -e log -argu 88
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 13
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 14
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 15
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 16
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 52
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 53
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 54
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 55
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 56
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 57
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 58
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 59
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 61
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 63
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 69
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 74
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 75
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 76
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 77
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 78
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 79
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 80
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 81
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 82
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 83
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 84
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 85
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 86
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 87
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 88
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 89
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 90
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 91
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 92
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 93
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 94
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 95
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 96
hep_sub ./script/fit_gamma_nonlin.sh -o log -e log -argu 97
