config = {
    "energy_scale":9892.6279/2.22,
    "gamma_electron_distribution":"./input/gamma_electron_tao.root",
    "cherenkov_template":"./input/TAO_Cherenkov.csv",
    "de_dx_file":"./input/ESTAR_GdLS.txt",
    "scint_nonlin_map_file":"./input/scint_nonlin_map.csv",
    "cherenkov_file":"./input/TAO_Cherenkov.csv",
    "e_dis_file":"./input/gamma_electron_tao.root",
    "radioactive_source":{
        "Cs137":{
            "energy":0.662,
            "label":"$^{137}Cs$",
            "gamma_num":1,
            "file_path":"/dybfs/users/xuhangkun/SimTAO/offline/change_data/neutron_design/2Weight_Enclosure_Ref_0.95/Cs137.root",
            "file_num":1,
            "calib_time":36000,
            "activity":50,
            "e_dis_name":"hECs"
            },
        "Mn54":{
            "energy":0.835,
            "label":"$^{54}Mn$",
            "gamma_num":1,
            "file_path":"/dybfs/users/xuhangkun/SimTAO/offline/change_data/neutron_design/2Weight_Enclosure_Ref_0.95/Mn54.root",
            "file_num":1,
            "calib_time":36000,
            "activity":50,
            "e_dis_name":"hEMn"
            },
        "Ge68":{
            "energy":1.022,
            "label":"$^{68}Ge$",
            "gamma_num":2,
            "file_path":"/dybfs/users/xuhangkun/SimTAO/offline/change_data/neutron_design/2Weight_Enclosure_Ref_0.95/Ge68.root",
            "file_num":1,
            "calib_time":100,
            "activity":500,
            "e_dis_name":"hEGe"
            },
        "K40":{
            "energy":1.461,
            "label":"$^{40}K$",
            "gamma_num":1,
            "file_path":"/dybfs/users/xuhangkun/SimTAO/offline/change_data/neutron_design/2Weight_Enclosure_Ref_0.95/K40.root",
            "file_num":1,
            "calib_time":36000,
            "activity":10,
            "e_dis_name":"hEK"
            },
        "Co60":{
            "energy":2.506,
            "label":"$^{60}Co$",
            "gamma_num":2,
            "file_path":"/dybfs/users/xuhangkun/SimTAO/offline/change_data/neutron_design/2Weight_Enclosure_Ref_0.95/Co60.root",
            "file_num":1,
            "calib_time":36000,
            "activity":10,
            "e_dis_name":"hECo"
            },
        "nH":{
            "energy":2.22,
            "label":"n-H",
            "gamma_num":1,
            "file_path":"",
            "file_num":1,
            "calib_time":36000,
            "activity":2*0.1,
            "e_dis_name":"hEnH"
            },
        "O16":{
            "energy":6.13,
            "label":"$^{16}O^{*}$",
            "gamma_num":1,
            "file_path":"",
            "file_num":1,
            "calib_time":36000,
            "activity":2*0.08,
            "e_dis_name":"hEO16"
            }
        }
}
